### PR TITLE
Update py-mtcli to 1.7.0, uniform schema for addOnParameters.

### PR DESCRIPTION
**Pull request by sugarraysam**

### CODE REVIEW

**Review by sandhyadalavi — APPROVED** [review]
lgtm

**Comment by erdii** [comment]
https://github.com/mt-sre/managed-tenants-cli/compare/1.6.4...main

**Comment by mayankshah1607** [comment]
I'm wondering if this should have instead been a patch release (1.6.5) , because I am not sure if the `imageset.addOnParameter` counts as a new feature. Technically, we only modified a feature that already exists. 🤔 

I know we can't revert this, but just a thought 😅

**Comment by sugarraysam** [comment]
You are probably right. I thought breaking the schema deserved at least a minor release but idk

**Pull request merged**
