### PR TITLE
[draft]Imageset subscription config support

### PR DESCRIPTION
**Pull request by ashishmax31**
Update tooling to support subscription configs in imageset files.

### CODE REVIEW

**Comment by mayankshah1607** [comment]
I'm not quite sure why we should be versioning subscription configs. IMO this would just make things slightly complicated as now managed-tenants-bundles and CPaaS would both be responsible for ensuring that subscription configs are populated within the imagesets.

Let's see what others think

**Comment by ashishmax31** [comment]
>I'm not quite sure why we should be versioning subscription configs.
It'd be for the same reason for which we've versioned `addOnParameters `, `subOperators` etc. In that line of logic, i think even subscription_config should be versioned.(Especially since the features supported by SubscriptionConfig are more than just passing env variables.)

**Comment by ashishmax31** [comment]
@yashvardhan-kukreja Your approach could work, although the tenants -> cpaas interface would still have to accommodate this feature (to keep it clean, would be a bad design to ask tenants to come and modify the imageset files created by cpaas.)

**Comment by ashishmax31** [comment]
Will reopen this PR with the mentioned approach

**Pull request closed without merging**
