### PR TITLE
[MTSRE-600] added upgradeStrategy for additionalCatalogSources

### PR DESCRIPTION
**Pull request by rpriyanshu9**
Signed-off-by: Priyanshu Raj <prraj@redhat.com>

# py-mtcli

## Description

Short description of the change:

added `upgradeStrategy` for additionalCatalogSources.
https://issues.redhat.com/browse/MTSRE-600

### CODE REVIEW

**Comment by apahim** [comment]
No need to parametrize this, we can set a sane default.

**Comment by rpriyanshu9** [comment]
Ack. What default time interval do you suggest?

**Comment by apahim** [comment]
Follow redhat-operators?
```
~$ oc get -n openshift-marketplace catalogsource redhat-marketplace -o json | jq .spec.updateStrategy
{
  "registryPoll": {
    "interval": "10m0s"
  }
}

```

**Comment by rpriyanshu9** [comment]
thanks, @apahim :)

**Pull request merged**
