### PR TITLE
More bundles changes

### PR DESCRIPTION
**Pull request by ashishmax31**
Adds some misc methods and functions which are required for migrating the code in mt-bundles repo

### CODE REVIEW

**Comment by yashvardhan-kukreja** [comment]
@ashishmax31 can you rebase this PR with main? (fixes the CI failures)

**Comment by sugarraysam** [comment]
Thanks for the continued refactoring @ashishmax31 . Another objective for this code migration was to add more testing. Can we think of a plan to test this `mtbundles` code, ideally as part of `pr_check.sh`?

There is the issue of exposing credentials in `ci.ext`, which we can't do in `pr_check.sh`. Our request to add an `OCM_TOKEN` was rejected: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/28706 

Should we move to `ci.int`? I would really like to see us building and pushing an index image as part of `pr_check.sh`. `quay.io/mt-sre-test/dummy-addon-<index|bundle>:<tag>`

**Comment by ashishmax31** [comment]
@sugarraysam Yep we need tests for this package. I've created a ticket to track this https://issues.redhat.com/browse/MTSRE-212. (I've left some thoughts on how to go about pushing images build during the tests, would love to see your thoughts as well.)
As for the ci-int move, i think we only move when the interaction environment with OCM is fixed, meaning, Are we going to get a new OCM environment to interact with during our tests? (We can't interact with OCM stage in our test code)

**Comment by mayankshah1607** [comment]
> Are we going to get a new OCM environment to interact with during our tests?

This is highly unlikely because of the number of other resources OCM depends on: Hive, DB, telemeter, etc.

**Review by mayankshah1607 — APPROVED** [review]

**Pull request merged**
